### ISSUE TITLE
Review function and module names in the codebase

### ISSUE THREAD

**Issue by macgregordennis** [turinginc/credo-core-node#138]

**Comment by macgregordennis** [comment]
@malroc Per your recent comments, it'd be great if you could go through the codebase sometime and determine if there are any other function names or modules that you think are worth renaming. I've done so a few times myself already.

**Comment by macgregordennis** [comment]
Note: I plan to rename all remaining references to `irreversible` in the codebase since it's too absolute.

**Comment by malroc** [comment]
@macgregordennis btw I have reviewed function/module names through the code base and consider them mostly clean and descriptive
