### ISSUE TITLE
Consider requiring a new timelock on a deposit after the previous one has expired.

### ISSUE THREAD

**Issue by macgregordennis** [turinginc/credo-core-node#142]

**Comment by malroc** [comment]
@macgregordennis I think this can be closed now as with the latest changes the wallet receives `no_deposit` as miner status in this case and can notify a user that mining was stopped and ask to submit another deposit in this case.

**Comment by macgregordennis** [comment]
@malroc Agreed. As a separate related issue, we may add an option to automatically renew/extend a deposit's timelock in settings at some point.
