### ISSUE TITLE
Support fees lower than 0.5 credo.

### ISSUE THREAD

**Issue by macgregordennis** [turinginc/credo-core-node#146]
This currently throws an error.

**Comment by malroc** [comment]
@macgregordennis the reason for this is that `0.5` credo is the minimal tx fee defined as constant here:
https://github.com/turinginc/credo-core-node/blob/master/lib/credo_core_node/blockchain/block_validator.ex#L15
I can just set it to any other value. What is your suggestion?

**Comment by macgregordennis** [comment]
@malroc I should have added a more detailed issue description: I defined the minimum transaction fee as `0.5` credo because lower values result in an error. Here are two examples illustrating the bug for the value and fee fields:

<img width="986" alt="screen shot 2019-03-06 at 10 52 40 pm" src="https://user-images.githubusercontent.com/1322709/53937650-9ad2f500-4062-11e9-89bc-2673279cdcfb.png">

<img width="992" alt="screen shot 2019-03-06 at 10 54 35 pm" src="https://user-images.githubusercontent.com/1322709/53937746-dec5fa00-4062-11e9-91eb-120bb14eedef.png">

As you can see, `generate_pending_transaction` throws an error when either the fee or value field is set to a decimal value below 0.5 such as 0.1

**Comment by malroc** [comment]
@macgregordennis #182 fixes the issue from the screenshot, I can now either set minimal fee to a lower level or remove it at all, what do you think about that?

**Comment by macgregordennis** [comment]
@malroc Let's keep a minimum fee to prevent spam transactions. Something like 0.01 Credo is fine for now.
