### ISSUE TITLE
eleveldb fails to build on latest Mac OS X versions

### ISSUE THREAD

**Issue by malroc** [turinginc/credo-core-node#147]
In short, `leveldb` sources included in the `eleveldb` version we use fail to build as the latest XCode versions don't include `libstdc++` which is considered obsolete.
A short workaround is to add ` -stdlib=libc++` to build options at:
`./deps/eleveldb/c_src/leveldb/build_config.mk#9`
`./deps/eleveldb/rebar.config.script#9`
A better solution would be to fork the latest `eleveldb` version (we currently use a very old one) and commit the appropriate fix like this:
https://github.com/basho/eleveldb/pull/245
But the latest version failed to compile on my machine for different reason, hence for now just posting a simple workaround if someone else needs it.

**Comment by macgregordennis** [comment]
@malroc I'm encountering this issue now too. Trying out the workaround. Let's fork and fix the `eleveldb` repo soon.

**Comment by macgregordennis** [comment]
Upgrading OSX/Xcode resolved the issue for me.

**Comment by macgregordennis** [comment]
I still have to manually implement this workaround after I clean dependencies, so it'd be good to either fork the related dependency and apply the patch or have another way to override the `eleveldb` version sometime soon.
