### ISSUE TITLE
Add mechanism to ensure correct miner state for each block.

### ISSUE THREAD

**Issue by macgregordennis** [turinginc/credo-core-node#218]
See https://github.com/turinginc/credo-core-node/pull/216

**Comment by i1t** [comment]
@malroc You were going to implement writing miners state as a special block transaction — you're going to implement that, correct? CC @macgregordennis

**Comment by macgregordennis** [comment]
@i1t Right. Do you want to handle #219 and #220?

**Comment by i1t** [comment]
@macgregordennis, yes, once #218 is implemented. We need to ensure that blocks contain miners state (the list of eligible miners with participation rates, ideally sorted by priority to propose a block in descending order, though the latter seems optional) before introducing the checks. Without that miners won't be in sync when doing the checks, just like they are currently likely to be out of sync when determining block proposer.

**Comment by malroc** [comment]
> @malroc You were going to implement writing miners state as a special block transaction — you're going to implement that, correct? CC

@i1t right, I'm currently working on it
