### ISSUE TITLE
Duplicate / false slashes might be included in a block and then applied

### ISSUE THREAD

**Issue by i1t** [turinginc/credo-core-node#223]
Since all nodes run `Slasher` to detect slashable behavior, it seems possible for more than one node to detect the same slashable incident and do `Pool.propagate_pending_transaction()` for generated slash trasnactions. Then `BlockProducer` or block proposer node might include more than 1 such transaction for the same slashable incident. Then `State.calculate_world_state_with_block/1` will apply all of confirmed transactions.

Speaking of `State.calculate_world_state_with_block/1`, it seems OK for it to apply all confirmed transactions and not do any extra validations. I think we should place those validations to block producer code.

We have `data.byzantine_behavior_proof` for pending slash transactions. We may use this field to clearly identify slashable incidents and prevent duplicates, and ensure the proofs are complete. For example, if slashee voted for 3 block candidates (A, B, C) for given height and round, the complete proof would include slashee's votes for A, B, and C. However, a proof with votes for B and C (without A) is a proof as well, so are proofs for A+B and A+C. The complexity here is that some nodes might not receive any of slashee's votes and will submit limited (unintentionally incomplete) proofs. Therefore, we shouldn't rely on complete `data.byzantine_behavior_proof`, but we should ensure a node is slashed exactly once for multi-chain voting for a given block.

Another question is which slash transaction should be accepted (in case we have multiple identical reactions to slashable behavior, which would be a common case). We could accept the earliest or pseudo-randomly select slasher among slash transaction submitters, proportionally to stake amounts (optionally).

We should also prevent falsification in slash transactions. `Slash.valid_slash_proof?/1` checks that submitted proof _would be valid, should it in fact exist_. Right now it's possible to slash any node by claiming we've got multiple votes from it for a given block & round — even if no other nodes got such votes, slash transaction would be accepted. We may need to get slash confirmations from multiple nodes, but that could also be overridden if a hacker launches a set of coordinated nodes all of which confirm the false slashes.

We also need to slash for false slashing (including slashing of false slashing of proper slashing). Right now false slashing seems the easiest way for hackers to steal funds from legitimate users.

**Comment by i1t** [comment]
@macgregordennis 

> I wouldn't use weighting by stake size because slashes could be submitted by non-miners.

Makes sense.

> I'm not sure if this is a problem. If a miner has a proof that's valid, it doesn't necessarily matter if other nodes received those votes.

That brings us to definition of slash proof validity. If slasher runs a modified node (which is trivial) and claims another node has cheated (when it in fact didn't) and submitted multiple votes per round (but no other nodes received them), is it a valid slash proof? Right now false slashing is rewarded by the system, and that's a concern.

**Comment by malroc** [comment]
@macgregordennis I've read the discussion and I agree with your position.
I think this is the only thing we need to fix:

>  I think we need to include an additional block validation to check that any included slash transactions are in fact valid. This way, other nodes would reject a block produced by a modified node that attempts to apply a false slash. We may also want to limit blocks to only including a single slash transaction per slasher per block to simplify validation logic (i.e. remove the need for potential sorting problems).

Will submit a fix in an hour.

**Comment by i1t** [comment]
@macgregordennis @malroc The above sounds good to me. `Mining.Slash.valid_slash_proof?/1` should validate signatures of votes from proof to ensure all votes in proof are valid, agreed?

**Comment by macgregordennis** [comment]
@i1t Agreed
