### ISSUE TITLE
Don't use Poison for encoding transactions data

### ISSUE THREAD

**Issue by malroc** [turinginc/credo-core-node#226]
When encoding maps, `Poison` relies on the built-in Elixir/Erlang key ordering which is *not guaranteed*. As a result, we can't rely on what a resulting string is. Which means that the hash of a transaction with `Poison`-encoded `data` is ambiguous, as the hash relies on the `data` string value.
This may cause a lot of problems in future. We need to implement JSON data encoder that always preserves keys in the same order.

**Comment by macgregordennis** [comment]
> We need to implement JSON data encoder that always preserves keys in the same order.

@malroc It'd be good to thoroughly check for such an encoder doesn't already exist before we implement something.

**Comment by malroc** [comment]
@macgregordennis implementing encoder is simple enough (unlike implementing decoder), so I tend to prefer implementing it on our side to make sure we actually control what the output is.
