### ISSUE TITLE
Mining synchronisation

### ISSUE THREAD

**Issue by i1t** [turinginc/credo-core-node#235]
Nodes need to come to consensus on what is current retry number for the pending block mining.

In `MineOperator`, calling
```
        @blockchain.last_locally_validated_block()
        |> @mining.start_mining(0)
```
is invalid since it blindly sets `retry_count` to 0, while there could be a number of mining retries made for the pending block height. `BlockProducer.is_your_turn?/2` depends on proper `retry_count`. If we sequentially launch 10 nodes with interval of `@block_production_timeout` (10 seconds) and no block would be mined during this time, each of them will have different `retry_count` value and likely have different opinion on which node should propose the next block.

Moreover, in the above scenario the nodes aren't synchronized in terms of starting the mining cycle, so if we launch them with interval of 5 seconds, block proposer would only have 5 seconds to propose a block (half of the nodes are started with 5 seconds shift, so `@block_production_timeout` effectively gets halved) — in reality the picture would be worse since the shifts would be random and effective "common window" for block proposing and acceptance would be unpredictable.

In order to resolve the above, I propose the following:

* `timestamp` field is added to Block / PendingBlock
* each node would be able to determine the current retry number by subtracting `block.timestamp` from `DateTime.utc_now()` and dividing the result by `@block_production_timeout` (where `block` is the last locally validated Block)
* in order to sync the cycles, each node would either wait until the next retry (if there's less than `@block_production_timeout / 2` to wait) or perform a short cycle (if there's less than `@block_production_timeout / 2` passed since the beginning of current cycle), and all subsequent cycles would be of full duration (`@block_production_timeout`) and started simultaneously with other nodes starting their cycles

**Comment by i1t** [comment]
@macgregordennis @malroc, pl. approve.

**Comment by macgregordennis** [comment]
@i1t Great solution
