### ISSUE TITLE
Make private key to address mappings exactly match Ethereum mainnet (to simplify migration for users).

### ISSUE THREAD

**Issue by macgregordennis** [turinginc/credo-core-node#242]

**Comment by malroc** [comment]
@macgregordennis currently working on it, will provide a working solution by Tuesday.

**Comment by macgregordennis** [comment]
@malroc Great, thanks

**Comment by malroc** [comment]
@macgregordennis I was using the wrong algorithm for calculating public key hash.
Fixed and should match eth pk -> address mapping now (see #247)

**Comment by macgregordennis** [comment]
@malroc Got it. Awesome to get this updated.
