### ISSUE TITLE
Implement incentive to slash.

### ISSUE THREAD

**Issue by macgregordennis** [turinginc/credo-core-node#52]

**Comment by macgregordennis** [comment]
@malroc @nishantj @i1t I think this could be implemented via a special case value transfer in the world state logic (i.e. a case statement [here](https://github.com/turinginc/credo-core-node/blob/master/lib/credo_core_node/state/state.ex#L123-L149)) for valid slash transactions in which slashed value is transferred from the slashee to the slasher. What do you guys think?

**Comment by malroc** [comment]
@macgregordennis one important thing to mention: if we want to do that via a special case in state calculation logic, we need to implement this before the mainnet launch, otherwise we'll either have inconsistent state on mainnet, or a complex backwards-compatibility code block which I would like to avoid.

**Comment by macgregordennis** [comment]
@malroc Agreed

**Comment by macgregordennis** [comment]
One problem with this approach is that attackers could theoretically claim the reward for detecting slashable behavior from another account that they control. I think we need to make the reward/incentive for slashing be only part of the slashed value. I'm hesitant to burn value/tokens, so the remainder may go to some other system account.

**Comment by macgregordennis** [comment]
@malroc One problem with this idea is that attackers could theoretically claim the reward for detecting slashable behavior from another account that they control. I think we need to make the reward/incentive for slashing be only part of the slashed value. I'm hesitant to burn value/tokens, so the remainder may go to some other system account.

**Comment by macgregordennis** [comment]
Resolved via #124.
